title: "David Fernando Lopez"
name: "David Fernando Lopez Alanis"
description: "Undergraduate student in Computer Technologies Engineering at Universidad de Monterrey (UDEM). UX/UI designer with experience in web and mobile front-end."
url: "https://davidlopeza.github.io"
locale: "en-US"

theme: minima
minimal_mistakes_skin: "default"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"

markdown: kramdown
highlighter: rouge
encoding: "utf-8"
timezone: "America/Mexico_City"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

analytics:
  provider: false

og_image: "profile.jpg"
og_description: "Personal academic website of David Fernando Lopez Alanis"
